### ISSUE TITLE
Grow Pgh gardens update

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#101]
Ellie to look into whether Grow PGH can update their garden sites for us.

**Comment by hellonewman** [comment]
6/16 update: Have an email in for getting updated data. I think we should just remove the gardens in the meantime and add them back in whenever we get the new file.

**Comment by maxachis** [comment]
> 6/16 update: Have an email in for getting updated data. I think we should just remove the gardens in the meantime and add them back in whenever we get the new file.

[Done.](https://github.com/CodeForPittsburgh/food-access-map-data/commit/0c5650d5f5af4b8ac9034e1b500bca3702210fdd)

**Comment by hellonewman** [comment]
Was intro'd to Grow Pgh CEO on 6/20. Followed up 6/22.

**Comment by hellonewman** [comment]
Received data and sent on to @cgmoreno for processing.

**Comment by hellonewman** [comment]
Closed thanks to @cgmoreno !
