### ISSUE TITLE
Summer meals sites

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#102]
@melynnduh to see if DHS/food bank data excludes City of Pgh schools.

@cgmoreno to see if USDA source encompasses summer meals sites.

**Comment by hellonewman** [comment]
@melynnduh any update on your piece?

**Comment by hellonewman** [comment]
Catalina found that USDA sites includes schools. Melinda waiting to hear from new food bank data person on whether GCPFB data has summer meal sites as well. If it does then we will use GCPFB instead. 

We should also do some checking into what sites are included, where they are, if they are just schools or other types of free meal sites.

**Comment by hellonewman** [comment]
6/16 update: Melinda confirmed with Food Bank that this dataset is the most accurate and up to date dataset for summer feeding sites for the kiddos. https://covid19-resource-mapping-alcogis.hub.arcgis.com/datasets/583200ff5aba427fac4f3509fdb0578e/explore?layer=0&location=40.411258%2C-79.518872%2C9.00&showTable=true

**Comment by maxachis** [comment]
@hellonewman With the 6/16 update, what else is remaining for this issue? The part about checking what sites are included and information about them?

**Comment by hellonewman** [comment]
Closed, thanks to @cgmoreno
