### ISSUE TITLE
Swap Just Harvest source data for Google Sheets

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#103]
to be discussed

**Comment by hellonewman** [comment]
codeforpittsburgh@gmail.com is now permissioned to access the Google Sheets file. @conorotompkins what do you need from me to set this up? Can I set up a Github Secret with the account info like we did for the Mapbox api?

**Comment by conorotompkins** [comment]
@hellonewman can you point me to the data source? once I have that I can put together the script to pull from Google Sheets

cc: @maxachis

**Comment by conorotompkins** [comment]
@hellonewman do you know which sheets we need to pull data from?

these are the ones I see:
`[1] "Just Harvest - Fresh Corners"   
[2] "Just Harvest - Fresh Access Mar"
[3] "GPCFB - Green Grocer"           
[4] "Additional Food Bucks sites"    
[5] "GoalsData Sources"              
[6] "Bridgeway Capital - HFFI Funds "`

**Comment by hellonewman** [comment]
I think it is just harvest fresh corners and just harvest fresh access market. You'd be able to check what sheets are used in the existing process. Forget if that is a Drew script, Cat script, or someone else.

**Comment by hellonewman** [comment]
@conorotompkins I just ran that code, looks like it worked. Can you check it out and close the issue if everything looks good?

**Comment by conorotompkins** [comment]
@hellonewman looks good to me, closing this issue
