### ISSUE TITLE
Replace references to "students" or "under 18/under 21" with "Young Populations"

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#122]
The label called "OpenToSpec" group is a non-binary label with different levels, one of them is "Student Population", but it's not clear what this applies to. Students 18 and younger is one of the listed sub-labels, as is "Students". But these categories are ambiguous. We're currently grouping these disparate populations under the umbrella label of "Students", but is this the best approach, or are we missing information? People might think this also applies to college students, but is that accurate?

**Comment by maxachis** [comment]
@hellonewman Will ask Sarah for clarification on this.

**Comment by hellonewman** [comment]
@maxachis Sarah/PFPC wants us to replace any reference to "students" or "under 18/ under 21" with "young populations".

**Comment by maxachis** [comment]
So next step would be to identify what code needs to be changed.
open_to_spec_group is referenced within schema.xlsx, but is that the only place it's located? I'm searching in other areas, but would like other's input to make sure I'm not missing anything.

**Comment by maxachis** [comment]
Additionally, make sure README is updated with new label description in label section.

**Comment by maxachis** [comment]
Looks like open_to_spec_group is also referenced in a number of prep files. I'm assuming every place where this is referenced in the prep files would need to be changed.

**Comment by hellonewman** [comment]
Cat did this! thanks Cat.
