### ISSUE TITLE
What to do about schema.xlsx?

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#123]
So I came across this while doing some spring cleaning. This schema, last updated by Drew, God Rest His Soul, in February of last year. There are notes to update various data columns, but honestly, I think we've done a lot of updates to this on our own, so do we even need this?

[schema.xlsx](https://github.com/CodeForPittsburgh/food-access-map-data/blob/master/schema.xlsx)

**Comment by hellonewman** [comment]
@cgmoreno Don't you use that file for your R script?

**Comment by maxachis** [comment]
To clarify, there are some rows in this Excel spreadsheet that appear to be marked for deletion.

![image](https://user-images.githubusercontent.com/48846180/124040441-edbedc00-d9d2-11eb-8441-23077adf4073.png)

This might require modifying the R script if we deem it necessary. So @cgmoreno  -- Should we remove those rows? Or leave it as is?

**Comment by maxachis** [comment]
Cat let me know that the things marked to be removed can indeed be removed. I've created a pull request that does just that at #142
