### ISSUE TITLE
Add way to datestamp ArcGIS Map Data

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#135]
Right now, it's difficult to determine what date our ArcGIS Map Data is from. Is it our most recently updated one, or a previous version than the one most recent in the Github? 

We would like a way that we, or someone on the frontend, could determine how old the data is. This could be anything from having the filename referenced be datestamped, to having a secret location on the map itself that references it, to adding a new attribute somewhere in the data that specifies the date.

**Comment by hellonewman** [comment]
@conorotompkins will investigate possibilities to add a date stamp column in the bash script.
