### ISSUE TITLE
Test public view/no auth on googlesheets4 package

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#148]
This one's for @conorotompkins. We found the google account-level authorization in the prep_Just_Harvest_Google_Sheets.R script (not the exact title) isn't working in our workflow, so we need to test switching to a public (anyone with a link can view) google sheet workbook and see if a no-auth approach will work.

Conor will switch the link to 
https://docs.google.com/spreadsheets/d/1LT1lssZFVcUH-07a9XhbzalpvV_mrSb3dNOd3ln20xQ/

and use the deauth() function in googlesheets4 as needed. https://googlesheets4.tidyverse.org/articles/articles/auth.html

**Comment by conorotompkins** [comment]
made https://github.com/CodeForPittsburgh/food-access-map-data/pull/149 for this issue

**Comment by hellonewman** [comment]
@maxachis ready for you to test run.sh again and see if it runs successfully.

**Comment by maxachis** [comment]
Runs successfully. Closing issue.
