### ISSUE TITLE
BUG?: Source data not being updated after run.sh

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#163]
Wicresults.json should be updating each time run.sh is run but appears to have not been updated in 2 months:
[https://github.com/CodeForPittsburgh/food-access-map-data/tree/master/food-data/new-datasets](https://github.com/CodeForPittsburgh/food-access-map-data/tree/master/food-data/new-datasets) 

This appears to be because of an odd bug where, as far as I can tell, the APIs and everything are running properly,  but the source data files aren't being committed and added to the Github during the run script. They're being generated, just not saved (at least I think that's what's happening).

**Comment by hellonewman** [comment]
reconfigure the YAML file.

**Comment by maxachis** [comment]
Si we do know that the information wicresults.json draws from hasn't had new data for at least four months. So simply making sure the master branch updates the proper subfolder properly should do the trick, but it could be made a bit more efficient if we could add a timestamp to wicresults.json (the text of the file, not the filename itself) to indicate when it was most recently updated.

**Comment by maxachis** [comment]
I added to run.sh Matt's script that is supposed to create wicresults.json and add a timestamp to it, but at least right now that code doesn't appear to be yielding a wicresults.json file with a timestamp. Will need to get back to this later and revise the script.

**Comment by maxachis** [comment]
Issue resolved and closed.
