### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by ajaxlex** [CodeForPittsburgh/food-access-map-data#164]
I have been trying to figure out what I need to do next to get my branch into the repository, and have been thinking about various git workflows that I have used for group projects and internal work.

The GitHub community profile checklist recommends, among other things, a "contributing guidelines" to round out the [community profile](https://github.com/CodeForPittsburgh/food-access-map-data/community).  The info I am looking for would fit nicely in such a document, and this would smooth out onboarding in the future.

Sorry if this info is already around and I missed it!

**Comment by maxachis** [comment]
Among things to add would be talking about how other people could contribute by forking the repo, rather than getting access to modify the main repo. Just as a security thing, and also so we don't run the risk of someone fat-fingering the delete button on the main repo.

**Comment by hellonewman** [comment]
[approved]
