### ISSUE TITLE
Figure out good process for data updating

### ISSUE THREAD

**Issue by melynnduh** [CodeForPittsburgh/food-access-map-data#18]
This might be a little premature, but at some point we'll need to outline how each dataset in our merged-data-csv gets updated.

This might be creating some shell website/place where a non-technical organization like Just Harvest can upload their updated list of food sites when they add/remove a place. More technical orgs like the food bank might be able to schedule a dump of food pantry data every month. 

Then we would want to schedule some monthly/quarterly/annually (?) job to look for new data and re-merge and update the dataset that feeds the app.

PFPC asked if we could document the process each org should follow for updating so she can help coordinate this. It would also be great if we could build her a little view showing the last updated date for each dataset.

**Comment by joshnygaard** [comment]
Several of the data sources are from [WPRDC](http://www.wprdc.org), as an example [data-conveniencesupermarkets.xlsx](https://data.wprdc.org/dataset/allegheny-county-supermarkets-convenience-stores). I believe it would be possible to pull this data through their [API](http://www.wprdc.org/data-wizards/)

**Comment by hellonewman** [comment]
Closing this as it has been further developed in more recent Issues
