### ISSUE TITLE
Mapping: fix icon pulls

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#182]
Icons are based on the field "type" with the following variables:
"convenience store" "farmer's market"   "food bank site"    "Grow PGH Garden"   "summer meal site" 
"supermarket"  

However the code seems to be pulling things differently: 

function getIcon(type) {
  if (type === "supermarket") {
    return superIcon;
  }
  if (type === "convenience store") {
    return convIcon;
  }
  if (type === "fresh access") {
    return freshIcon;
  }
  if (type === "farmers market") {
    return farmerIcon;
  }

The "farmers market" should be "farmer's market". There is no type of "fresh access" in the data. And we should have icons for the gardens, food bank sites, and summer meal sites.

**Comment by hellonewman** [comment]
We also need new icons for:
food bank site (something that denotes it is free?)
summer meal site (sunshine?)

**Comment by maxachis** [comment]
Partial fix applied with [this commit](https://github.com/CodeForPittsburgh/food-access-map-data/commit/596ca706d315eb0561b8863ae838b5d4f016ee90).

Full fix requires new icons, per Ellie's comment above.

**Comment by melynnduh** [comment]
do these new icons work? they were somehow sized large, but that doesn't matter, right? https://github.com/CodeForPittsburgh/food-access-map/tree/master/app/images

**Comment by hellonewman** [comment]
Just one piece left- someone needs to replace the links in lines 31-38 with Melinda's new icons.
https://github.com/CodeForPittsburgh/food-access-map-data/blob/596ca706d315eb0561b8863ae838b5d4f016ee90/frontend/script.js 

https://github.com/CodeForPittsburgh/food-access-map/blob/master/app/images/food_bank_03.png will be the food bank icon.

https://github.com/CodeForPittsburgh/food-access-map/blob/master/app/images/summer_food.png will be the summer food site icon.
