### ISSUE TITLE
Mapping: add side panel table with site info

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#183]
This feature request is for a sidebar site info table. similar to the AGOL one: https://www.arcgis.com/apps/instant/nearby/index.html?appid=6315c774b49540689eac60bce9e0c8bd

The AGOL map has you click on the map to establish a radius, then populates the side table with info about the sites within that radius.

Our table does not need to be as slick. Ideally, it would pretty much have the same info as the map popups, like:
- Site name
- Site type
- Address
- Link to google transit directions
- Programs (listing things like: SNAP, WIC, fresh produce, etc., if =1)

**Comment by maxachis** [comment]
This link here includes a possible leaflet sidebar that we could implement
https://github.com/Turbo87/leaflet-sidebar

**Comment by maxachis** [comment]
Pull request for a (not completely finished) version of this.

https://github.com/CodeForPittsburgh/CodeForPittsburgh.github.io/pull/20

**Comment by maxachis** [comment]
Because the pull request was merged, can we do a final check to make sure the current format of the website meets the desired specifications (oooh very formal terminology, ho ho)

**Comment by hellonewman** [comment]
we have a side panel!
