### ISSUE TITLE
Create Mockups of Filter/Search

### ISSUE THREAD

**Issue by ryangeraghty** [CodeForPittsburgh/food-access-map-data#187]
As a team, we want to mock up a few ways to arrange the filter and search tools on both mobile and desktop screen sizes so that users can get the correct information on resources that they need. 

**Search:** Used to focus the geographic area to a target point (using address or place, i.e. Garfield or Pittsburgh, or 5000 Forbes Ave Pittsburgh, PA 15213

**Distance Filter:** Used to limit results to a certain distance.  Currently this is fixed at 1 mile as the crow flies from the search point.

**Benefit Type Filter:** Used to filter based on the types of benefits that are accepted at an establishment, i.e. SNAP, WIC, etc,

**Establishment Type Filter:** Used to filter by the kind of location you are interested in, i.e. Full service Grocery Store, Limited Grocery Store/Market, Food Pantry, Convenience Store, Farmers Market, etc.

Deliverable: 2-3 rough design mockups to discuss and improve upon

@hellonewman can you assign this to me, I can't seem to do so myself.

**Comment by ryangeraghty** [comment]
Here is the [working file](https://docs.google.com/presentation/d/1vGiHACsGjmdoHvW28cclCEQKeaZyefe07YkZJKtTdIw/edit?usp=sharing) of mockups for what filtering could look like.  I will continue to work on this and report at the next meeting if not before.

**Comment by hellonewman** [comment]
Thanks Ryan! We like where this is going. We're thinking about starting with a splash screen with buttons for site type and access type where the user can select what they are interested in, then it pulls up a filtered map.

**Comment by maxachis** [comment]
Filter and search put together, so comfortably closing this!
