### ISSUE TITLE
Add Onboarding Wizard

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#188]
Have a small onboarding wizard at startup -- a small text bubble that greets the user, introduces the app, and points out the search section on the side of the screen. Once you do it the first time, a cookie remembers that you've done this, and you don't have to do it when starting the app up again.

Possibly make it even less obtrusive by simply having the filter/search buttons flash briefly at startup.

**Comment by hellonewman** [comment]
Matt says there is a tool for this! He'll look up what it is called but it should make an easy fill-in-the-blank for this project.

**Comment by hellonewman** [comment]
here it is! https://introjs.com

**Comment by maxachis** [comment]
https://introjs.com/ is one possible option.

**Comment by hellonewman** [comment]
I think this is great as a first pass. I'll review with PFPC and see what they think.
