### ISSUE TITLE
Style the map filters as buttons and/or toggles

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#189]
We'd like to see how our map filters might look as buttons or check boxes instead of filters. This explains how to style buttons/toggles in Bootstrap: https://getbootstrap.com/docs/5.0/forms/checks-radios/#toggle-buttons

Map code is located in our Github.io repo: https://github.com/CodeForPittsburgh/CodeForPittsburgh.github.io/tree/master/FoodAccessMap 

Ideally by next meeting, we'd have these options styled as buttons:
 Supermarket

 Convenience Store

 Grow PGH Garden

 Farmer's Market

And these styled as toggles:
 SNAP

 WIC

 FMNP

 Food Bucks

 Fresh Produce

 Free Distribution

And we can see which we like best. Feel free to experiment with different styling/colors etc.

**Comment by runstache** [comment]
I took a stab at this one from last night and utilized the existing Bootstrap.  

Was able to implement Toggle switches and organize each of the items into groups. If this looks good, I'll open a PR on it.
<img width="472" alt="Screen Shot 2022-03-31 at 9 05 11 PM" src="https://user-images.githubusercontent.com/13137742/161175388-f25505ad-03fc-4542-8d35-df0bd1ac1dca.png">

**Comment by hellonewman** [comment]
@runstache yes this is beautiful! exactly what we were looking for.
