### ISSUE TITLE
Location types should be standardized

### ISSUE THREAD

**Issue by qualitymanifest** [CodeForPittsburgh/food-access-map-data#19]
Assuming that the data coming from https://dev.stevesaylor.io/api/location/ is current with what is here, some improvements that could be made to the location types:
- Ideally would be one case style - sticking with snake-case would be good
- Ideally would have just one type each
- Should probably combine `null` and `other`

Here are the types at present:
```
Farmers Market
null
Convenience Store
Supermarket
sustainability-fund-site|other
other
grow-pittsburgh-site
community-farm
community-farm|school-garden
school-garden
commercial-urban-farm|grow-pittsburgh-site
commercial-urban-farm
allegheny-grows-site
sustainability-fund-site
community-garden
sustainability-fund-site|school-garden
allegheny-grows-site|sustainability-fund-site
```

**Comment by hellonewman** [comment]
I'll check out what types are currently listed and come up with a suggested grouping methodology for the group to review.

**Comment by hellonewman** [comment]
Here are the current types:
`# type                  n
 * <chr>             <int>
 1 convenience store   421
 2 Farm Market          43
 3 Farm Stand           46
 4 farmer's market      17
 5 food bank site      560
 6 fresh access         22
 7 Grow PGH Garden      80
 8 summer meal site    285
 9 supermarket         166
10 NA                  429`

Looks like farm market, farm stand, and farmer's market should be combined. Fresh access should be categorized by location type (add manually?) Finally, lots of NAs. 

Looking just at these types brings up these source files as culprits:

` type            source_file                                   n
  <chr>           <chr>                                     <int>
1 Farm Market     FMNPMarkets.xlsx                             43
2 Farm Stand      FMNPMarkets.xlsx                             46
3 farmer's market GPCFB - Green Grocer.xlsx                    17
4 fresh access    Just Harvest - Fresh Access Markets.xlsx     22
5 NA              Additional Food Bucks sites.xlsx              3
6 NA              Allegheny_County_WIC_Vendor_Locations.csv    35
7 NA              SNAP_Store_Locations.csv                    391`

So, I propose we
- create a combined "farm stand or market" for FMNPMarkets.xlsx and GPCFB Green Grocer
- manually type the Fresh Access Markets and Additional Food Bucks Sites in a new field
- explore generating a type from the store name for Allegheny_County_WIC_Vendor_Locations.csv and SNAP_Store_Locations.csv (see #55 )

**Comment by hellonewman** [comment]
Decided to ignore all except NAs. @conorotompkins will try to categorize SNAP na's to come up with location type rules.

**Comment by hellonewman** [comment]
https://github.com/CodeForPittsburgh/food-access-map-data/issues/55 closing bc duplicate
