### ISSUE TITLE
Fix Typesetting Bug

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#198]
A script called prep_snap.R that is pulling in sites from SNAP. We thought it was categorizing them by type and saying if the type is a farmer's market or supermarket, then type is 1. But we create a type field and just put NA in it, because were trying to determine a type by name, like if it contains Giant Eagle it's a supermarket, etc., but we moved that to a different script that might be downstream. So we're saying that supermarkets have fresh produce but the script doesn't know what site is a supermarket yet so we haven't told it yet. 

So we need to find where we're identifying things as supermarkets or fresh produce.

**Comment by maxachis** [comment]
Look into the Floats issue, Max! Ellie says look into it.

**Comment by maxachis** [comment]
Looks like the floats issue isn't a problem now! For record-keeping's sake, I've attached an xlsx file that compares the merged_datasets.csv in the master branch to the one in the new branch. Have a look at it, and if it looks good, I think we can merge!

[textcompare.xlsx](https://github.com/CodeForPittsburgh/food-access-map-data/files/8789561/textcompare.xlsx)

**Comment by hellonewman** [comment]
max fixed
