### ISSUE TITLE
Add 2 New Site Type Filter Buttons, with Associated Functionality

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#199]
Filters are "Summer Meal Site" and "Food Bank Site"

**Comment by hellonewman** [comment]
I realized I forgot one additional site type! There's a type of "Other" that also should be on the map/filterable.

**Comment by hellonewman** [comment]
@[runstache](https://github.com/runstache) could be a good one for you! ^

**Comment by runstache** [comment]
@hellonewman I added to filter to the Types but I'm not seeing any items in the backend dataset to truly test it.  It should work since it's pretty much just a variation on the existing items.

**Comment by maxachis** [comment]
On hold pending cleanout of code. Apparently type other still isn't appearing, and we can't figure out why, so a code cleanup in CodeForPittsburgh/food-access-data-transformation#1 will likely help.

**Comment by hellonewman** [comment]
Larry fixed!
