### ISSUE TITLE
Many of the coordinates are reversed

### ISSUE THREAD

**Issue by qualitymanifest** [CodeForPittsburgh/food-access-map-data#20]
As with the last issue, this is assuming that the data at https://dev.stevesaylor.io/api/location/ is current with what is here. If it is, 134 of the coordinates are reversed and end up in Antarctica, and a few of the other ones end up in Russia or Europe.

**Comment by MappingMary** [comment]
I QC'd the merged dataset and I fixed some of the outliers.  
[merged_datasets.xlsx](https://github.com/CodeForPittsburgh/food-access-map-data/files/4232603/merged_datasets.xlsx)
![image](https://user-images.githubusercontent.com/11170368/74970700-d4744b80-53ec-11ea-8c02-88fedd9bad06.png)

**Comment by qualitymanifest** [comment]
Looks good, do you want to open a PR with that @MappingMary

**Comment by hellonewman** [comment]
Closed- Max re-geocoded all the sites using Mapbox.
