### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by lodenrogue** [CodeForPittsburgh/food-access-map-data#213]
Hi. I just discovered your wonderful repository. I think this is really great work! I wanted to know if there was any interest in dockerizing the application so that new contributors (and old as well) have an easier time installing the necessary dependencies and getting started with contributions.

If there's an interest I can try to take a crack at it.

**Comment by maxachis** [comment]
I'm definitely interested in seeing how this works! I can't guarantee the dockerization will occur until after we've seen how it works and we can have a sense of how it compares to the current method. If you would like to work on that, and give a timetable for how long you figure it'd take, I'm certainly interested!

**Comment by hellonewman** [comment]
We ended up remaking the repo and the new version has dockerization already. Thanks @lodenrogue for the idea!
