### ISSUE TITLE
Improve Farmer's Market Type Setting

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#214]
Currently, there are rows in our data that include the term "Farmer's Market" (or the grammatically incorrect "Farmers Market" variant) which do not have their type set as "farmer's market".

For example:

BELLEVUE FARMERS MARKET	34 N Balph Avenue	Pittsburgh	PA
GREEN TREE FARMER'S MARKET IN THE PARK	905 Greentree Road	Pittsburgh	PA

Both of these have nothing in their type. This can screw up front-end labeling as well as deduplication. We can probably safely label these as "Farmer's Market" and make things easier for ourselves.

The "auto_text_process_name.R" file could be adjusted for this -- all you'd need to do is add "FARMERS MARKET" and "FARMER'S MARKET" to the "farmers_market" list variable (yes, I know that phrase was confusing), and it should take care of itself. All we'd need is a bit of testing to make sure nothing else weird occurs -- probably just a simple csv compare between the old resultant dataset and our new dataset.

One wrench in this is the below row:

FRESH THYME FARMERS MARKET 452PLH	665 Clairton Boulevard	Pittsburgh	PA

This is labeled as a "Supermarket", and a google search suggests that is indeed what it is, albeit one that focuses on locally sourced produce. "auto_text_process_name.R" already accounts for this and properly labels it as "supermarket", so we probably don't need to make any changes, but something to keep an eye out for.

**Comment by maxachis** [comment]
This issue is also discussed/related to https://github.com/CodeForPittsburgh/food-access-map-data/issues/215

**Comment by hellonewman** [comment]
Larry fixed!
