### ISSUE TITLE
Examine and Optimize de_dup_fun.R

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#47]
Catalina Moreno already developed a deduplication script, located in de_dup_fun.R within food-access-map-data/data_prep_scripts/de_dup_fun.R. Cat thinks the script could be improved, or that we may want to use other alternatives, so it is a good candidate to examine in our deduplication research. And if we can modify it to improve its functionality, all the better. 

A sub-issue of #16 - Dedupe food stores in merged dataset

**Comment by hellonewman** [comment]
@maxachis is this the basis of your merge_duplicates.R script? If so I think you can close this.

**Comment by maxachis** [comment]
> @maxachis is this the basis of your merge_duplicates.R script? If so I think you can close this.

Yup! Closing it now.
