### ISSUE TITLE
process new farmers market data

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#53]
the new farmers market datasource needs to be wrangled into our schema.

**Comment by hellonewman** [comment]
Mary and Drew- this looks like it was done [here](https://github.com/CodeForPittsburgh/food-access-map-data/blob/master/data_prep_scripts/2020-10-20_prep_sources_MKohl.py ), is it missing anything? If it's gtg then please close this

**Comment by marykohl3** [comment]
I am pretty sure that is it?

**Comment by hellonewman** [comment]
Drew will remove the old FMNP stuff from his script and then @drewlevitt please close this issue when done.

**Comment by drewlevitt** [comment]
I commented out the farmers market ingestion bits from my script so we should be good to go!
