### ISSUE TITLE
Geocoding: modularize process

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#56]
ensure geocoding function works across all scripts, not just R scripts (Max)

**Comment by maxachis** [comment]
I'm on it!

**Comment by maxachis** [comment]
I think I'll just need a bit more clarification on this one.

Right now, the Geocoding script is called by "run_new_data_merge.R", and is partly dependent on data drawn from that script. As I understand it, "modularize" in this context means to ensure it can be called itself, not within any other scripts, and that it takes an input file and outputs an intermediate output file that will then be ingested by some other script.

Do I have that right, @hellonewman?

**Comment by maxachis** [comment]
I'll also say that I probably need #54 and #55 to complete before I can comfortably complete this, as it is dependent on those prior intermediate steps, @cgmoreno.

**Comment by maxachis** [comment]
Cat has taken care of this, so I think we can mark it as complete!
