### ISSUE TITLE
Script to flag potential duplicates (Super De Duper!)

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#57]
I am hoping either @cgmoreno could provide more detail or Matt knows what this is referring to!

**Comment by hellonewman** [comment]
Ah, I think this was it: (from Catalina's ppt)
Duplication id step  Matt
Euclidean dist check 🡪 group1
String dist check + numeric address check + green grocer rules + food bank rule🡪 group2

**Comment by hellonewman** [comment]
3/16 update: Matt's script produces 3 columns...each increases in granularity (or does it). Testing step only uses 1 of these columns. Need to figure out which column to weight most. 

Next step: select one option based on the unit testing. Then Matt will implement 1 of them.

**Comment by hellonewman** [comment]
Matt + MAX to discuss today

**Comment by maxachis** [comment]
Script to flag potential duplicates been added. Now only issue is unit testing.
