### ISSUE TITLE
Securely storing project keys and passwords?

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#65]
We've got a few passwords and access keys floating around. If one of us gets raptured or whatever, we probably want to make sure that person wasn't the only one to know what the password or access key to something is, or that we have them stored somewhere safe. Not sure what this would look like in practice, but probably should keep it on our roadmap.

**Comment by maxachis** [comment]
Found a solution! We can store them on Github using Github Secrets!

https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by hellonewman** [comment]
we did it!
