### ISSUE TITLE
Cleanup Files in Repository

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#83]
We have a few files in the repository that are outdated and no longer needed. One is [Geocoding.R](https://github.com/CodeForPittsburgh/food-access-map-data/blob/master/geocoding.R), located in the root directory. We can probably safely remove that one, and likely others as well. We should review this at some point!

**Comment by hellonewman** [comment]
Go for it @maxachis! (but keep a local copy just in case)

**Comment by maxachis** [comment]
This is complete! Archived files can be found in https://github.com/CodeForPittsburgh/food-access-map-data/tree/master/archive .
