### ISSUE TITLE
Remove "auto_" from finished data prep scripts?

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-map-data#84]
Right now, the "auto_" in front of many of the scripts in the [data_prep_scripts](https://github.com/CodeForPittsburgh/food-access-map-data/tree/master/data_prep_scripts) folder is important because we haven't yet transitioned to making all of the scripts a part of our automated script process. Eventually, though, once that transition is complete, it might be worthwhile to remove them, as they don't really tell us much about the files if every one inside the folder has that in its name. Not a big deal either way, but just something to keep an eye out for as we do cleanup.

**Comment by hellonewman** [comment]
Eh, I kind of like leaving them as is. One, it reminds us how good we are at automation. Two, not changing the names = less work = good!
