### ISSUE TITLE
Categorize SNAP locations by type

### ISSUE THREAD

**Issue by conorotompkins** [CodeForPittsburgh/food-access-map-data#88]
Using the location name (about 420 NA’s currently)

**Comment by conorotompkins** [comment]
@hellonewman @cgmoreno @maxachis can we clarify the file name and column I should be looking at? I think it is "cleaned_PA_SNAP.csv" column "type"

**Comment by hellonewman** [comment]
@conorotompkins Possibly it was me who was confused...It looks like you, @cgmoreno and @maxachis are all authors on [this script ](https://github.com/CodeForPittsburgh/food-access-map-data/blob/master/data_prep_scripts/auto_text_process_name.R)that categorizes based on name like Target, Aldi etc? 

Is this already working and incorporated in our master data workflow?
